export enum ActionTypes {
  GET_MEMBER_DETAILS_REQUEST = "GET_MEMBER_DETAILS_REQUEST",
  GET_MEMBER_DETAILS_SUCCESS = "GET_MEMBER_DETAILS_SUCCESS",
  GET_MEMBER_DETAILS_FAILURE = "GET_MEMBER_DETAILS_FAILURE"
}
